spring.application.name=football-intelligence-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:football_db}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:root}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
football.api.token=${FOOTBALL_API_TOKEN:91292f92cd994081aae51db3a33b2d9b}

spring.devtools.restart.enabled=false
